"""Added new columns

Revision ID: 7d616964973b
Revises: 
Create Date: 2026-03-01 22:55:45.106869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d616964973b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_guides_share_token'), 'guides', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guides_share_token'), table_name='guides')
    op.drop_column('guides', 'share_token')
    # ### end Alembic commands ###
